apiVersion: apps/v1
kind: Deployment
metadata:
  name: go-echo-server
  labels:
    app: go-echo-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: go-echo-server
  template:
    metadata:
      labels:
        app: go-echo-server
    spec:
      terminationGracePeriodSeconds: 60
      containers:
      - name: go-echo-server
        image: dotlou/go-echo-server:v0.0.3
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8080
        resources:
          limits:
            cpu: 10m
            memory: 20Mi
          requests:
            cpu: 10m
            memory: 20Mi
---
apiVersion: v1
kind: Service
metadata:
  name: go-echo-server
  labels:
    app: go-echo-server
spec:
  ports:
  - port: 8080
    targetPort: 8080
  selector:
    app: go-echo-server
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: go-echo-server
  annotations:
    kubernetes.io/ingress.class: "nginx"
    nginx.ingress.kubernetes.io/auth-url: http://go-echo-server.default.svc.cluster.local:8080/fakeAuth
    nginx.ingress.kubernetes.io/auth-response-headers: Authorization
spec:
  rules:
  - http:
      paths:
      - backend:
          serviceName: go-echo-server
          servicePort: 8080
        path: /
